# Generated by Django 3.1.7 on 2021-04-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=50)),
                ('introduce', models.TextField()),
                ('shoppingmall', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Main_Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('image_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FaQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('kind', models.CharField(max_length=20)),
                ('top10', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QnA_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('question_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QnA_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
